permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : Yong Cha
tagline: Programmer and Potter
author :
  name : Yong Cha
  email : 
  github : yocha
  twitter : 
  feedburner : 

production_url : http://yocha.github.com

JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  comments :
    provider : disqus
    disqus :
      short_name : programmerandpotter
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-30665029-1'
  sharing :
    provider : false
